from __future__ import annotations

import repo_bootstrap  # noqa: F401

import argparse
from pathlib import Path

from ogse_fitting.resampled_contrast_outputs import export_resampled_contrasts_from_fits
from ogse_fitting.resampled_contrast_outputs import VALID_GRID_MAX_MODES, VALID_RESAMPLED_CONTRAST_MODES


def _split_csv(value: str | None) -> list[str] | None:
    if value is None or str(value).strip() == "" or str(value).upper() == "ALL":
        return None
    return [x for x in str(value).replace(",", " ").split() if x]


def main() -> None:
    ap = argparse.ArgumentParser(
        description=(
            "Export OGSE contrasts generated by subtracting independently fitted signal curves "
            "on a corrected common-gradient grid."
        )
    )
    ap.add_argument("fits_root", type=Path, help="Root folder containing OGSE contrast fit_params.")
    ap.add_argument("--contrast-root", type=Path, required=True, help="Direct contrast root containing tables/.")
    ap.add_argument("--out-dir", type=Path, required=True, help="Output directory for resampled contrast folders.")
    ap.add_argument("--pattern", default="**/fit_params.*", help="Relative glob used to discover fit_params inside fits_root.")
    ap.add_argument("--grid-min-mTm", type=float, default=0.0, help="Corrected common-gradient minimum in mT/m.")
    ap.add_argument("--grid-max-mTm", type=float, default=90.0, help="Corrected common-gradient maximum in mT/m.")
    ap.add_argument(
        "--grid-max-mode",
        choices=VALID_GRID_MAX_MODES,
        default="fixed",
        help=(
            "How to choose the upper corrected-gradient limit: fixed uses --grid-max-mTm; "
            "observed_pair_max uses the maximum corrected gradient observed across the two signal curves."
        ),
    )
    ap.add_argument("--grid-n", type=int, default=1000, help="Number of points in the corrected common-gradient grid.")
    ap.add_argument(
        "--contrast-mode",
        choices=VALID_RESAMPLED_CONTRAST_MODES,
        default="signal_fit",
        help=(
            "signal_fit subtracts the fitted signal curves directly, including any offset/noise term; "
            "rest_only subtracts M_ogse_rest curves reconstructed from the fitted parameters."
        ),
    )
    ap.add_argument("--models", default=None, help="Comma- or space-separated model filter, or ALL.")
    ap.add_argument("--subjs", default=None, help="Comma- or space-separated subject filter, or ALL.")
    ap.add_argument("--rois", default=None, help="Comma- or space-separated ROI filter, or ALL.")
    ap.add_argument("--directions", default=None, help="Comma- or space-separated direction filter, or ALL.")
    ap.add_argument("--peak-D0-fix", type=float, default=3.2e-12, help="Fixed D0 used for derived axes.")
    ap.add_argument("--peak-gamma", type=float, default=267.5221900, help="Gamma in rad/(ms*mT) used for derived axes.")
    ap.add_argument("--g-min-derived", type=float, default=0.0, help="Minimum g (mT/m) above which to compute Ld/lcf/Lcf/tc; below this threshold values are NaN.")
    ap.add_argument("--include-failed", action="store_true", help="Include rows with ok=False.")
    args = ap.parse_args()

    outputs = export_resampled_contrasts_from_fits(
        fits_root=args.fits_root,
        contrast_root=args.contrast_root,
        out_dir=args.out_dir,
        pattern=str(args.pattern),
        grid_min_mTm=float(args.grid_min_mTm),
        grid_max_mTm=float(args.grid_max_mTm),
        grid_max_mode=str(args.grid_max_mode),
        grid_n=int(args.grid_n),
        contrast_mode=str(args.contrast_mode),
        models=_split_csv(args.models),
        subjs=_split_csv(args.subjs),
        rois=_split_csv(args.rois),
        directions=_split_csv(args.directions),
        peak_D0_fix=float(args.peak_D0_fix),
        peak_gamma=float(args.peak_gamma),
        ok_only=not bool(args.include_failed),
        g_min_derived=float(args.g_min_derived),
    )
    print(f"[OK] Exported resampled contrast tables: {len(outputs)}")
    for path in outputs[:20]:
        print(f"  - {path}")
    if len(outputs) > 20:
        print(f"  ... {len(outputs) - 20} more")


if __name__ == "__main__":
    main()
